server:
  port: 8082

financial-service:
  base-url: ${CORE_DATA_SERVICE_BASE_URL:http://financial-service:8082}
logging:
  level:
    com.financial.report.infrastructure.presentation.version: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/projeto_impiricus
    username: impiricus
    password: impiricus
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # create, create-drop, validate, none, update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
alpha-vantage:
  api-key: ${ALPHA_VANTAGE_API_KEY}
  base-url: https://www.alphavantage.co/query
  timeout: 30000  # 30 segundos
bull-market-api:
  base-url: ${BULL_MARKET_URL_API:https://sua-api-interna.com/api}